version: "3.7"
services:
  database:
    container_name: spring-db
    image: mariadb
    ports:
    - 3306:3306
    volumes:
      - C:\Users\박범선\datadir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
  application:
    ports:
    - 8080:8080
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always


