spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: myadmin
    password: qkrqjatjs15
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #show-sql: true
    properties:
      hibernate:
        format_sql: true

