spring:
  redis:
    host: localhost
    port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:tcp://localhost/~/redistest