# Service

apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo-app-service
  type: LoadBalancer

---

## Deployment

apiVersion: apps/v1


kind: Deployment

metadata:
  name: demo-app-service


spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-app-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # kubectl set image deployment demo-app demo-app=beomsun22/k8s-app
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo-app-service

    spec:
      containers:
        - name: hello-k8s-app-service
          image: beomsun22/k8s-app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always