#도커에서 제공하는 스토리지가 있으므로 name = hostpath

# kubectl get storageclasses.storage.k8s.io ->동적 볼륨을 위한 스토리지 클래스 리소스 확인
apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mariadb-pv-claim

spec:
  storageClassName: hostpath

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi